### ISSUE TITLE
Consider removing the "Source input isn't a file" warning

### ISSUE THREAD

**Issue by dominikwilkowski** [Velenir/babel-plugin-import-redirect#34]
When compiling react from a string this plugin will warn via https://github.com/Velenir/babel-plugin-import-redirect/blob/master/src/index.js#L17

To prevent it from warning you currently have to provide a fake filename in the `filename` key.

**Comment by Velenir** [comment]
I didn't consider your usecase. Would making it suppressible with `suppressResolveWarning` option work for you? Semantically it fits.

**Comment by dominikwilkowski** [comment]
Absolutely. That makes sense to me.

**Comment by Velenir** [comment]
Done:)

**Comment by dominikwilkowski** [comment]
Just as a note as it doesn't effect me really but now with your code change here: https://github.com/Velenir/babel-plugin-import-redirect/commit/cf1a7cb4433614b11d7343e6384bec615e42aa98#diff-1fdf421c05c1140f6d71444ea2b27638R16

When you got nothing defined it wont warn anymore. So now `suppressResolveWarning` doesn't need to be defined and you have to actually do `suppressResolveWarning: true` to see the warn...
Happy to submit a PR but it seems small :)

**Comment by dominikwilkowski** [comment]
Never mind. I had `suppressResolveWarning` already defined further up in the code :) Don't mind me
